name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: npm ci
      env:
        CI: true
    - name: Unit Tests
      run: npm test
    - name: Code Coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage/coverage-final.json
        flags: unittests
        fail_ci_if_error: true

  test:
    needs: build

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install
      run: npm ci
      env:
        CI: true
    - name: Integration Tests
      run: npm run test-integ
      env:
        SCOUT_EMAIL: ${{ secrets.SCOUT_EMAIL }}
        SCOUT_PASSWORD: ${{ secrets.SCOUT_PASSWORD }}
